import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import useNetwork from '@/data/network'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const {network, isLoading, isError } = useNetwork()
 
  if (isLoading) return <div>Loading...</div>
  if (isError) return <div>Error...</div>

  const stations = network.stations;

  console.log(network);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Welcome to Cycle&nbsp;
            <code className={styles.code}></code>
          </p>
        
        </div>

        <div className={styles.grid}>
        
          <a
            href="#stations"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Bikes <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find your available bike in Antwerp.
            </p>
          </a>

          <a
            href="#prices"
            className={styles.card}
            rel="noopener noreferrer"
          >
            <h2 className={inter.className}>
              Prices <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Check out our Day, Week and Annual Cards.
            </p>
          </a>
          <br/>
        </div>

        <Image
          src="/Antwerp.png"
          alt="Antwerp City"
          className={styles.Antwerp}
          width={400}
          height={400}
          priority
        />

        <div id="stations" className={styles.div_stations} >
          <h1 className={styles.station}>Available stations</h1>
            {stations.slice(0, 3).map(station => (
          <p className={styles.stations} key={station.id}>
            {station.name}<br/>Free Bikes: {station.free_bikes}<br/>Empty Spots: {station.empty_slots}
          </p>

          ))}
        </div>
        <div id="prices" className={`${styles.div_prices} ${styles.prices_section} ${styles.center_align}`}>
  <h1 className={`${styles.station} ${styles.heading} ${styles.bigger_font}`}>Our Prices</h1>
  <div className={styles.content}>
    <div className={styles.price_container}>
      <div className={styles.price}>
        <p className={styles.price_type}>Day Pass</p>
        <p className={styles.price_value}>5 Euro</p>
      </div>
      <div className={styles.price}>
        <p className={styles.price_type}>Week Pass</p>
        <p className={styles.price_value}>12 Euro</p>
      </div>
      <div className={styles.price}>
        <p className={styles.price_type}>Year Pass</p>
        <p className={styles.price_value}>58 Euro</p>
      </div>
    </div>
    <button className={styles.button}>Choose Your Pass Type</button>
  </div>
</div>


      </main>
      

    </>
  )
}
